services:
  db:
    image: postgis/postgis:17-3.5-alpine
    platform: linux/amd64
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: heimdall
      POSTGRES_USER: heimdall
      POSTGRES_PASSWORD: heimdall
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
