"""initial schema

Revision ID: 27d1dff153fa
Revises: 
Create Date: 2026-03-22 04:24:24.840910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '27d1dff153fa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('listing_type', sa.String(length=10), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('city', sa.Text(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('region', sa.Text(), nullable=False),
    sa.Column('postal_code', sa.Text(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('sqft', sa.Numeric(), nullable=True),
    sa.Column('price_per_sqft', sa.Numeric(), nullable=True),
    sa.Column('coordinates', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('crawled_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'address', 'listing_type', name='uq_source_address_type')
    )
    op.create_index('ix_listings_city', 'listings', ['city'], unique=False)
    op.create_index('ix_listings_coordinates', 'listings', ['coordinates'], unique=False, postgresql_using='gist')
    op.create_index('ix_listings_country', 'listings', ['country'], unique=False)
    op.create_index('ix_listings_listing_type', 'listings', ['listing_type'], unique=False)
    op.create_index('ix_listings_postal_code', 'listings', ['postal_code'], unique=False)
    op.create_index('ix_listings_region', 'listings', ['region'], unique=False)
    op.create_table('zip_metrics',
    sa.Column('postal_code', sa.Text(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('region', sa.Text(), nullable=False),
    sa.Column('lat', sa.Numeric(), nullable=True),
    sa.Column('lng', sa.Numeric(), nullable=True),
    sa.Column('avg_buy_price_per_sqft', sa.Numeric(), nullable=True),
    sa.Column('avg_rent_per_sqft', sa.Numeric(), nullable=True),
    sa.Column('rent_to_price_ratio', sa.Numeric(), nullable=True),
    sa.Column('listing_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('postal_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zip_metrics')
    op.drop_index('ix_listings_region', table_name='listings')
    op.drop_index('ix_listings_postal_code', table_name='listings')
    op.drop_index('ix_listings_listing_type', table_name='listings')
    op.drop_index('ix_listings_country', table_name='listings')
    op.drop_index('ix_listings_coordinates', table_name='listings', postgresql_using='gist')
    op.drop_index('ix_listings_city', table_name='listings')
    op.drop_table('listings')
    # ### end Alembic commands ###
